#spring.datasource.driverClassName
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/rest_with_spring_boot_udemy
    username: root
    password: password
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect


